OG-566 Hub penalize fix
opengsn/gsn pull request #659
Opened 2021-06-21 18:34 UTC by shahafn

2021-06-23 20:27 UTC, drortirosh approved these changes

2021-06-23 20:28 UTC, drortirosh requested changes
the hub penalization fix looks OK, but it depends on a complex boosting issue, which looks much more complex (and unrelated..)

2021-06-25 10:02 UTC, shahafn commented
> the hub penalization fix looks OK, but it depends on a complex boosting issue, which looks much more complex (and unrelated..)

Yes, once we merge the previous PR, I'll rebase this one and you'll see only the diff.

2021-06-27 20:36 UTC, drortirosh approved these changes

2021-06-27 20:37 UTC, drortirosh requested changes
missing version change

2021-06-27 20:41 UTC, shahafn commented
> missing version change

Do you mean contract version?

2021-06-30 17:52 UTC, drortirosh commented on packages/provider/src/GSNConfigurator.ts
> +  requiredVersionRange: '2.2.3',
this is the one version we should not update: you basically say that you don't want to run against contracts with older version.

2021-07-01 09:20 UTC, drortirosh approved these changes

2021-07-01 12:26 UTC, merged